converse/urls.py
from django.urls import path
from django.views.generic import RedirectView, DeleteView, DetailView

from .models import *
from .views import *

urlpatterns = [
    path('register/', register),
    path('', RedirectView.as_view(url='order/', permanent=True), name='index'),

    path('person/',
         ListViewByUser.as_view(model=Person, queryset=Person.objects.order_by('level')),
         name="person_list"),
    path('person/detail/<int:pk>',
         UpdateView.as_view(model=Person,
                            fields=['name', 'level', 'phone', 'proof', 'address', 'group', 'description'],
                            template_name="converse/form_detail.html", success_url='/person'),
         name="person_detail"),
    path('person/add',
         PersonCreateView.as_view(),
         name="person_add"),
    path('person/delete/<int:pk>',
         DeleteView.as_view(model=Person, template_name="converse/confirm_delete.html",
                            success_url='/person'),
         name="person_delete"),

    path('stuff/',
         ListView.as_view(model=Stuff, queryset=Stuff.objects.order_by('level', 'id')),
         name="stuff_list"),
    path('stuff/update/<int:pk>',
         UpdateView.as_view(model=Stuff,
                            fields=['name', 'name_c', 'level', 'price', 'dose', 'comment', 'image'],
                            template_name="converse/form_detail.html", success_url='/stuff'),
         name="stuff_detail"),
    path('stuff/add',
         CreateView.as_view(model=Stuff,
                            fields=['name', 'name_c', 'level', 'price', 'dose', 'comment'],
                            template_name="converse/form_detail.html", success_url='/stuff'),
         name="stuff_add"),

    path('order/',
         ListViewByUser.as_view(model=Order,
                                queryset=Order.objects.filter(Q(paid=False) | Q(received=False))),
         name="order_list"),
    path('order_report/', order_report, name="order_report"),
    path('order/unpaid',
         ListViewByUser.as_view(model=Order, queryset=Order.objects.filter(paid=False)),
         name="order_list_unpaid"),
    path('order/unreceived',
         ListViewByUser.as_view(model=Order, queryset=Order.objects.filter(received=False)),
         name="order_list_unreceived"),
    path('order/recent/<int:days>',
         RecentOrderListView.as_view(),
         name="order_list_recent"),
    path('order/all', ListViewByUser.as_view(model=Order), name="order_list_all"),
    path('order/update/<int:pk>',
         OrderUserFieldFilterUpdateView.as_view(),
         name="order_update"),
    path('order/detail/<int:pk>',
         DetailView.as_view(model=Order),
         name="order_detail"),
    path('order/add',
         OrderCreateView.as_view(),
         name="order_add"),
    # path('order/by_delivery/<int:pk>',
    #     UpdateView.as_view(model=Order, fields=['person', 'stuff', 'amount'],
    #                        template_name="converse/form_detail.html", success_url='/orde'),
    #     name="order_detail"),

    path('order/confirm_paid/<int:order_id>', confirm_paid,
         name="order_confirm_paid"),
    path('order/confirm_unpaid/<int:order_id>', confirm_unpaid,
         name="order_confirm_unpaid"),
    path('order/confirm_received/<int:order_id>', confirm_received,
         name="order_confirm_received"),
    path('order/confirm_unreceived/<int:order_id>', confirm_unreceived,
         name="order_confirm_unreceived"),
    path('order/confirm_paid_received/<int:order_id>', confirm_paid_received,
         name="order_confirm_paid_received"),

    path('delivery/',
         ListView.as_view(model=Delivery, queryset=Delivery.objects.filter(order__received=False)),
         name="delivery_list"),
    path('delivery/all', ListView.as_view(model=Delivery), name="delivery_list_all"),
    path('delivery/update/<int:pk>',
         DeliveryUpdateView.as_view(),
         name="delivery_update"),
    path('delivery/detail/<int:pk>',
         DetailView.as_view(model=Delivery),
         name="delivery_detail"),
    path('delivery/add',
         DeliveryCreateView.as_view(),
         name="delivery_add"),

    path('delivery/status/<int:delivery_id>',
         delivery_status_list,
         name="delivery_status"),

    path('api/order/',
         api_order_list,
         name="api_order_list"),
    path('api/order/add',
         api_order_add,
         name="api_order_add"),
    path('api/order/delivery/',
         api_order_delivery,
         name="api_order_delivery"),
    path('api/order/delivery/add',
         api_order_delivery_add,
         name="api_order_delivery_add"),

]

hermes2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converse.urls')),

]

converse/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.utils.timezone import now


class PersonGroup(models.Model):
    name = models.CharField('群名', max_length=6)

    def __str__(self):
        return '{}: {}'.format(self.id, self.name)


class Person(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=CASCADE)
    name = models.CharField('名字', max_length=6)
    level = models.CharField('排序', max_length=15, blank=True, null=True, default='')
    address = models.TextField('地址', max_length=200, blank=True, null=True)
    description = models.TextField('注释', max_length=200, blank=True, null=True, default='')
    proof = models.CharField('身份证号码', max_length=18, blank=True, null=True)
    phone = models.CharField('电话号码', max_length=40, blank=True, null=True)
    image_front = models.ImageField('身份证正面', blank=True, null=True)
    image_back = models.ImageField('身份证反面', blank=True, null=True)
    group = models.ForeignKey(PersonGroup, verbose_name='群组', blank=True, null=True, on_delete=CASCADE)

    def __str__(self):
        return '{}: {}'.format(self.id, self.name)


class Stuff(models.Model):
    name = models.CharField('英文名', max_length=200)
    name_c = models.CharField('中文名', max_length=200)
    brand = models.CharField('品牌', max_length=40)
    level = models.CharField('排序', max_length=15, blank=True, null=True, default='')
    price = models.DecimalField('价格', max_digits=6, decimal_places=2, default=0)
    dose = models.CharField('剂量', max_length=100, blank=True, null=True)
    barcode = models.CharField('条形码', max_length=50, blank=True, null=True)
    image = models.ImageField('图片', blank=True, null=True)
    comment = models.CharField('注释', max_length=1000, blank=True, null=True)

    def __str__(self):
        return '{}: {}/{} '.format(self.id, self.name_c, self.name)


class Courier(models.Model):
    name = models.CharField(max_length=200)
    detail = models.TextField(max_length=800, blank=True, null=True)
    serial_regex = models.TextField(max_length=200, blank=True, null=True)
    rank = models.PositiveIntegerField(default=0, blank=True, null=True)
    status_url = models.TextField(max_length=400, blank=True, null=True)
    url_fields = models.TextField(max_length=400, blank=True, null=True)
    is_post = models.BooleanField(default=True)
    xpath_date = models.TextField(max_length=400, blank=True, null=True)
    xpath_location = models.TextField(max_length=400, blank=True, null=True)
    xpath_detail = models.TextField(max_length=400, blank=True, null=True)

    def __str__(self):
        return '{}: {}'.format(self.id, self.name)


class Order(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=CASCADE)
    person = models.ForeignKey(Person, verbose_name='顾客', on_delete=CASCADE)
    started = models.DateField('日期', auto_now_add=True, blank=True, null=True)
    price = models.DecimalField('总价', max_digits=6, decimal_places=2, default=0, blank=True, null=True)
    paid = models.BooleanField('已付款？', default=False)
    received = models.BooleanField('已收货？', default=False)
    detail = models.TextField('详单', max_length=1000, blank=True, null=True)

    def __str__(self):
        return '{}: {} {} '.format(self.id, self.person.name, self.detail[:10])


class Delivery(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=CASCADE)
    order = models.ForeignKey(Order, verbose_name='订单', on_delete=CASCADE)
    courier = models.ForeignKey(Courier, verbose_name='快递', blank=True, null=True, on_delete=CASCADE)
    serial = models.CharField('单号', max_length=50, blank=True, null=True)
    started = models.DateField('开始日期', default=now)
    image = models.ImageField('快递单照片', blank=True, null=True)
    comment = models.CharField('注释', max_length=200, blank=True, null=True)

    def __str__(self):
        return '{}: {}'.format(self.id, self.serial)

    class Meta:
        unique_together = ('user', 'order', 'serial')


class DeliveryStatus(models.Model):
    delivery = models.ForeignKey(Delivery, verbose_name='快递', on_delete=CASCADE)
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    d_date = models.CharField('更新日期', max_length=50)
    d_location = models.CharField('地点', max_length=50)
    d_detail = models.CharField('详情', max_length=50)

    def __str__(self):
        return '{}: {} / {}'.format(self.id, self.delivery.serial, self.date)


class AppKey(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    app = models.CharField('App', max_length=50)
    key = models.CharField('Key', max_length=50)

    def __str__(self):
        return '{}: {} / {} / {}'.format(self.id, self.user.username, self.app, self.key)

converse/views.py
from datetime import datetime, timedelta

from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, ListView, View, UpdateView
from django.views.generic.edit import ModelFormMixin, FormMixin
from django.views.generic.list import MultipleObjectMixin

from .models import Order, Delivery, DeliveryStatus, AppKey, Person


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)


def confirm_paid(request, order_id):
    if order_id:
        order = Order.objects.get(pk=order_id)
        if order:
            order.paid = True
            order.save()
    return HttpResponseRedirect('/order')


def confirm_unpaid(request, order_id):
    if order_id:
        order = Order.objects.get(pk=order_id)
        if order:
            order.paid = False
            order.save()
    return HttpResponseRedirect('/order')


def confirm_received(request, order_id):
    if order_id:
        order = Order.objects.get(pk=order_id)
        if order:
            order.received = True
            order.save()
    return HttpResponseRedirect('/order')


def confirm_unreceived(request, order_id):
    if order_id:
        order = Order.objects.get(pk=order_id)
        if order:
            order.received = False
            order.save()
    return HttpResponseRedirect('/order')


def confirm_paid_received(request, order_id):
    if order_id:
        order = Order.objects.get(pk=order_id)
        if order:
            order.received = True
            order.paid = True
            order.save()
    return HttpResponseRedirect('/order')


def delivery_status_list(request, delivery_id):
    if delivery_id:
        delivery = Delivery.objects.get(pk=delivery_id)
        status_list = DeliveryStatus.objects.filter(delivery=delivery)
        context = {'status_list': status_list}
        return render(request, 'converse/delivery_status_list.html', context)

    return HttpResponseRedirect('/order')


def order_report(request):
    show_group = request.GET.get('show_group', '')
    order_list = Order.objects.raw(
        'SELECT * FROM converse_order where received = 0 and id not in (select order_id from converse_delivery)')
    context = {'order_list': order_list, 'show_group': show_group}
    return render(request, 'converse/order_report.html', context)


def api_order_list(request):
    key = request.GET.get('key', '')
    app_key = AppKey.objects.filter(key=key)
    if app_key:
        orders = Order.objects.filter(Q(paid=False) | Q(received=False))
        json_dict = {}
        for order in orders:
            order_dict = {'person': order.person.name, 'detail': order.detail}
            json_dict[order.id] = order_dict
        return JsonResponse(json_dict)
    return JsonResponse({})


def api_order_add(request):
    key = request.GET.get('key', '')
    app_key = AppKey.objects.get(key=key)
    if app_key:
        person_id = request.GET.get('person_id', '')
        person = Person.objects.get(id=person_id)
        if person:
            detail = request.GET.get('detail', '')
            order = Order()
            order.person = person
            order.detail = detail
            order.save()

            return JsonResponse({order.id: {'person': person.name, 'detail': detail}})
    return JsonResponse({})


def api_order_delivery(request):
    key = request.GET.get('key', '')
    app_key = AppKey.objects.get(key=key)
    if app_key:
        order_id = request.GET.get('order_id', '')
        order = Order.objects.get(id=order_id)

        deliveries = Delivery.objects.filter(order=order)
        json_dict = {}
        for delivery in deliveries:
            json_dict[delivery.id] = delivery.serial
        return JsonResponse(json_dict)
    return JsonResponse({})


def api_order_delivery_add(request):
    key = request.GET.get('key', '')
    app_key = AppKey.objects.get(key=key)
    if app_key:
        order_id = request.GET.get('order_id', '')
        order = Order.objects.get(id=order_id)
        serial = request.GET.get('serial', '')
        if order and serial:
            delivery = Delivery()
            delivery.order = order
            delivery.serial = serial
            delivery.save()

            return JsonResponse({delivery.id: {'order': order.id, 'serial': serial}})
    return JsonResponse({})


def api_order_delivery_remove(request):
    key = request.GET.get('key', '')
    app_key = AppKey.objects.get(key=key)
    if app_key:
        delivery_id = request.GET.get('delivery_id', '')
        delivery = Delivery.objects.get(id=delivery_id)
        serial = delivery.serial
        if delivery:
            delivery.delete()
            return JsonResponse({delivery_id: serial})
    return JsonResponse({})


class DefaultUserMixin(ModelFormMixin, View):
    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(DefaultUserMixin, self).form_valid(form)


class PersonCreateView(DefaultUserMixin, CreateView):
    model = Person
    fields = ['name', 'level', 'phone', 'proof', 'address', 'group']
    template_name = "converse/form_detail.html"
    success_url = '/order'


class PersonFieldFilterMixin(FormMixin, View):
    def get_form(self, form_class=None):
        form = super(PersonFieldFilterMixin, self).get_form(form_class)
        form.fields['person'].queryset = Person.objects.filter(user=self.request.user)
        return form


class OrderCreateView(DefaultUserMixin, PersonFieldFilterMixin, CreateView):
    model = Order
    fields = ['person', 'detail', 'price', 'paid', 'received']
    template_name = "converse/form_detail.html"
    success_url = '/order'


class OrderUserFieldFilterUpdateView(PersonFieldFilterMixin, UpdateView):
    model = Order
    fields = ['person', 'detail', 'price', 'paid', 'received']
    template_name = "converse/form_detail.html"
    success_url = '/order'


class OrderFieldFilterMixin(FormMixin, View):
    def get_form(self, form_class=None):
        form = super(OrderFieldFilterMixin, self).get_form(form_class)
        form.fields['order'].queryset = Order.objects.filter(user=self.request.user)
        return form


class DeliveryCreateView(DefaultUserMixin, OrderFieldFilterMixin, CreateView):
    model = Delivery
    fields = ['order', 'serial']
    template_name = "converse/form_detail.html"
    success_url = '/order'

    def get_initial(self):
        order_id = self.request.GET.get('order_id', '')
        if order_id:
            order = Order.objects.get(id=order_id)
            return {
                'order': order,
            }


class DeliveryUpdateView(OrderFieldFilterMixin, UpdateView):
    model = Delivery
    fields = ['order', 'serial', 'courier']
    template_name = "converse/form_detail.html"
    success_url = '/order'

    def get_initial(self):
        order_id = self.request.GET.get('order_id', '')
        if order_id:
            order = Order.objects.get(id=order_id)
            return {
                'order': order,
            }


class FilterByUserMixin(MultipleObjectMixin, View):
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ListViewByUser(FilterByUserMixin, ListView):
    pass


class RecentOrderListView(ListViewByUser):
    model = Order
    ordering = ['-started']

    def get_queryset(self):
        days = self.kwargs['days']
        if days:
            return super().get_queryset().filter(started__range=(datetime.now() - timedelta(days=days),  datetime.now()))
        else:
            return super().get_queryset()

converse/templates/converse/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load staticfiles %}

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.png' %}"/>
    <link rel="apple-touch-icon" href="{% static 'image/favicon_64.png' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {#jquery#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    {#bootstrap#}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    {#jquery ui#}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <script src="{% static 'js/confirm.js' %}"></script>

    {% block head %}{% endblock %}

    <title>{% block title %}Hermes: 快递跟踪系统{% endblock %}</title>
</head>

<body>
<div style="display:none;" ><img src="{% static 'image/favicon_512.png' %}" /></div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Hermes</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="/order">订单</a></li>
                <li><a href="/person">客户</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/admin">Admin</a></li>
                <li><a href="/admin/logout">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div id="content" class="container" style="padding:0">
    {% block content %}{% endblock %}
</div>

</body>
</html>

converse/templates/converse/confirm_delete.html
{% extends "converse/base.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

converse/templates/converse/delivery_detail.html
{% extends "converse/base.html" %}

{% block content %}

    <table class="table table-striped table-hover">
        <tr>
            <td>Order</td>
            <td>
                <a href="/order/detail/{{ object.order.id }}"> {{ object.order.person.name }}</a>
                <br>
                {{ object.order.detail }}
            </td>
        </tr>
{#        <tr>#}
{#            <td>Company</td>#}
{#            <td> {{ object.company.name }} </td>#}
{#        </tr>#}
        <tr>
            <td>serial</td>
            <td> {{ object.serial }} </td>
        </tr>
        <tr>
            <td>started</td>
            <td> {{ object.started }} </td>
        </tr>
        <tr>
            <td>image</td>
            <td> {{ object.image }} </td>
        </tr>
        <tr>
            <td>comment</td>
            <td> {{ object.comment }} </td>
        </tr>
    </table>
{% endblock %}

converse/templates/converse/delivery_list.html
{% extends "converse/base.html" %}

{% block content %}

    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">操作
            <span class="caret"></span></button>
        <ul class="dropdown-menu">
            <li><a href="/delivery/add" >新增快递</a></li>
            <li><a href="/delivery/all">显示全部快递（包括已完成）</a></li>
        </ul>
    </div>

    <table class="table table-striped table-hover">
        <tr>
            <th></th>
            <th>收件人</th>
            <th>单号</th>
            <th>发货日期</th>
            <th>是否已结束</th>
{#            <th>注释</th>#}
            <th>订单详情</th>
{#            <th>命令</th>#}
        </tr>
        {% for delivery in object_list %}
            <tr>
                <td>
                    <form action="/delivery/update/{{ delivery.id }}" method="get">
                        <button class="btn btn-info"># {{ delivery.id }}</button>
                    </form>
                </td>
                <td>{{ delivery.order.person.name }}</td>
{#                <td>{{ delivery.company.name }} / {{ delivery.serial }}</td>#}
                <td>{{ delivery.started }}</td>
                <td>
                    {% if delivery.order.done %}
                        已结束
                    {% else %}
                        进行中
                    {% endif %}
                </td>
{#                <td>{{ delivery.comment }}</td>#}
                <td>
                    {{ delivery.order.detail }}
                </td>
{#                <td>#}
{#                    <a href="/delivery/update/{{ delivery.id }}">修改</a>#}
{#                    <br>#}
{#                    <a href="/order/update/{{ delivery.order.id }}">完成</a>#}
{#                    查看订单#}
{#                    确认结束#}
{#                </td>#}
            </tr>
        {% endfor %}
    </table>

{% endblock %}

converse/templates/converse/delivery_status_list.html
{% extends "converse/base.html" %}

{% block content %}

    <table class="table table-striped table-hover">
        <tr>
            <th>检查日期</th>
            <th>条目日期</th>
            <th>位置</th>
            <th>详情</th>
        </tr>
        {% for delivery_status in status_list %}
            <tr>
                <td>
                    {{ delivery_status.date | date:"m-d" }}
                </td>
                <td>
                    {{ delivery_status.d_date }}
                </td>
                <td>
                    {{ delivery_status.d_location }}
                </td>
                <td>
                    {{ delivery_status.d_detail }}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

converse/templates/converse/form_detail.html
{% extends "converse/base.html" %}

{% block content %}

    <form action="" method="post">
        <table class="table table-striped table-hover">
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        {% if object %}
            <input type="submit" value="Update"/>
        {% else %}
            <input type="submit" value="Create"/>
        {% endif %}
    </form>
{% endblock %}

converse/templates/converse/order_detail.html
{% extends "converse/base.html" %}

{% block content %}

    <table class="table table-striped table-hover">
        <tr>
            <td>ID</td>
            <td>{{ object.id }}</td>
        </tr>
        <tr>
            <td>Person</td>
            <td>
{#                <a herf="/order/detail/{{ object.order.id }}"> #}
                    {{ object.person.name }}
{#                </a>#}
            </td>
        </tr>
        <tr>
            <td>Detail</td>
            <td> {{ object.detail }} </td>
        </tr>
        <tr>
            <td>Started</td>
            <td> {{ object.started }} </td>
        </tr>
        <tr>
            <td>Paid</td>
            <td> {{ object.paid }} </td>
        </tr>
        <tr>
            <td>Done</td>
            <td> {{ object.done }} </td>
        </tr>
        {% for delivery in object.delivery_set.all %}
            <tr>
                <td>{{ delivery.id }}</td>
                <td>
                    <a href="/delivery/detail/{{ delivery.id }}">
                        {{ delivery.company.name }} / {{ delivery.serial }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

converse/templates/converse/person_list.html
{% extends "converse/base.html" %}{% block content %}    <a class="btn btn-primary" href="/person/add">新增客户</a>    <table class="table table-striped table-hover">        <tr>{#            <th></th>#}            <th>名字</th>            <th>电话</th>            <th>身份证号</th>            <th>地址</th>            <th>注释</th>{#            <th>操作</th>#}        </tr>        {% for person in object_list %}            <tr>                <td style="width: 10%">                  <a href="/person/detail/{{ person.id }}">                    {{ person.name }}                  </a>                </td>                <td style="width: 10%">{{ person.phone }}</td>                <td style="width: 20%">{{ person.proof }}</td>                <td style="width: 40%">{{ person.address }}</td>                <td style="width: 15%">{{ person.description }}</td>{#                <td style="width: 25%">#}{#                    <a href="/person/delete/{{ person.id }}">Delete</a>#}{#                </td>#}            </tr>        {% endfor %}    </table>{% endblock %}

converse/templates/converse/stuff_list.html
{% extends "converse/base.html" %}{% block content %}    <a class="btn btn-primary" href="/stuff/add">新增保健品</a>    <table class="table table-striped table-hover">        <tr>            <th>中文名</th>            <th>品牌</th>            <th>价格</th>        </tr>        {% for stuff in object_list %}            <tr>                <td>                    <a href="/stuff/detail/{{ stuff.id }}">{{ stuff.name_c }}</a>                </td>                <td>{{ stuff.brand }}</td>                <td>{{ stuff.price }}</td>            </tr>        {% endfor %}    </table>{% endblock %}